### PR TITLE
chore: github workflow for publishing to pub.dev

### PR DESCRIPTION
**Pull request by johannesvedder**
https://github.com/marketplace/actions/dart-and-flutter-package-publisher

### CODE REVIEW

**Comment by nstrelow** [comment]
I don't think we want to publish the app and designer package.

Also this is not using melos, so it cannot figure out in which order to upload the dependencies. 

But I think you can adjust the order of steps so it always first uploads:
1. core
2. flutter_common

**Comment by nstrelow** [comment]
Oh, and this seems totally fine and a great idea. Hope it works.

I think you should be able to do all the required steps now by yourself, but let me know if this is not the case.

**Review by nstrelow — APPROVED** [review]
Looks great if you added the secrets

**Comment by johannesvedder** [comment]
Thanks for the feedback. I'll leave the `dryRunOnly` field active for the next test run and remove it if everything works fine.

**Pull request merged**
