### PR TITLE
Bug: Monitoring 

### PR DESCRIPTION
**Pull request by rajuAhmed1705**
scope of testing:
https://trello.com/c/yOMuCoYa

### CODE REVIEW

**Comment by johannesvedder** [comment]
Is this ready for review? @rajuAhmed1705

**Comment by rajuAhmed1705** [comment]
@johannesvedder, except for the task with the intervention mismatch problem. everything is solved. I actually cannot create a study without an intervention task. So, I'm trying to figure out the other way around.

**Comment by johannesvedder** [comment]
> @johannesvedder, except for the task with the intervention mismatch problem. everything is solved. I actually cannot create a study without an intervention task. So, I'm trying to figure out the other way around.

This used to be possible in the past and we might need to re-enable this again in order to allow washout phases, as long as we have the adaptive schedule alternative. So you can revert [this commit](https://github.com/hpi-studyu/studyu/commit/825ea7fb269412f2afb26bae998288d984167174) if you would like.

**Comment by ibrahimozkn** [comment]
> > @johannesvedder, except for the task with the intervention mismatch problem. everything is solved. I actually cannot create a study without an intervention task. So, I'm trying to figure out the other way around.
> 
> This used to be possible in the past and we might need to re-enable this again in order to allow washout phases, as long as we have the adaptive schedule alternative. So you can revert [this commit](https://github.com/hpi-studyu/studyu/commit/825ea7fb269412f2afb26bae998288d984167174) if you would like.

#671

**Review by ibrahimozkn — CHANGES_REQUESTED** [review]
- UI overflow when language is set to German in bar chart legends and participant details legends
- Missing translation for ""Dropout"

image
image

**Review by ibrahimozkn — APPROVED** [review]
✅

**Pull request merged**
