### PR TITLE
Implement studies table with ListView

### LINKED ISSUE #497: Bug: Designer breaks when resizing window
See [Trello card](https://trello.com/c/yxAe26eh)

### LINKED ISSUE #516: Implement studies table with ListView
See https://trello.com/c/AKEq97B1/100-implement-studies-table-with-listview

### LINKED ISSUE #517: Bug: Sorting is broken on study registry
See https://trello.com/c/9sQkpxXH/101-bug-sorting-is-broken-on-study-registry

### PR DESCRIPTION
**Pull request by hig-dev**
The current implementation uses a Table which is not suitable for future additions such as expandable rows.

The new implementation also fixes resizing bugs and sorting.

Fixes #516 
Fixes #497 (for study registry)
Fixes #517

### CODE REVIEW

**Comment by johannesvedder** [comment]
I'd like to merge the huge PR https://github.com/hpi-studyu/studyu/pull/520 first before looking into this to avoid excessive merge conflicts with the other code.

And https://github.com/hpi-studyu/studyu/pull/510 and https://github.com/hpi-studyu/studyu/pull/511 would need to be rewritten since #518 most certainly collides with them.

**Comment by hig-dev** [comment]
I think we also need to add a horizontal scrollbar:

image

**Comment by johannesvedder** [comment]
#520 is ready now, could you check for compatibility issues of #520 and this PR?

And do you plan on integrating a horizontal scrollbar?

**Comment by hig-dev** [comment]
> And do you plan on integrating a horizontal scrollbar?

Yes, I think it is necessary.

**Comment by hig-dev** [comment]
Moved to #555

**Pull request closed without merging**
